"""
14b_finalise_rq1_rq2_reporting.py
=================================
TASK 14B -- Finalise RQ1/RQ2 statistical REPORTING before the Results are
            written. This is a reporting and robustness-cleanup task only.

NOTHING analytical is changed: preprocessing, analytical samples, linguistic
measures, model specification, eligibility rules, company mappings and event
windows are all fixed. The RQ1 model is re-fitted with the SAME specification
via the Task 14 module, so the estimates here are identical to Task 14's --
only the reporting around them changes. Task 14's result tables are NOT
overwritten; this task writes new `14b_*` files. RQ3 is not run.

WHAT CHANGES
------------
  1. RQ1 year contrasts gain a Holm-adjusted p-value alongside the raw one.
  2. RQ2 is standardised on ONE primary estimand and ONE primary test across
     all four measures, with Wilcoxon demoted to a distributional robustness
     check rather than being primary for one measure and not the others.
  3. Wording rules for non-significant results are applied and recorded.

Outputs
-------
processed/14b_rq1_year_contrasts_holm.csv
processed/14b_rq2_reporting_final.csv
qc/14b_rq1_rq2_reporting_report.txt
qc/14b_validation_results.csv

Run:
    .venv/bin/python 14b_finalise_rq1_rq2_reporting.py
"""

from __future__ import annotations

import datetime as dt
import importlib.util
import os
import sys

import numpy as np
import pandas as pd
import scipy.stats as st
from statsmodels.stats.multitest import multipletests

PROJECT_ROOT = os.path.dirname(os.path.abspath(__file__))
REPO_ROOT = os.path.dirname(PROJECT_ROOT)                       # repository root
_DATA = os.environ.get("ERP_DATA_DIR", os.path.join(REPO_ROOT, "data"))
_OUT  = os.environ.get("ERP_OUTPUT_DIR", os.path.join(REPO_ROOT, "outputs"))
PROCESSED_DIR = _DATA
QC_DIR = os.path.join(_OUT, "qc")

_spec = importlib.util.spec_from_file_location(
    "t14", os.path.join(PROJECT_ROOT, "14_analyse_rq1_rq2.py"))
t14 = importlib.util.module_from_spec(_spec)
_spec.loader.exec_module(t14)

_sspec = importlib.util.spec_from_file_location(
    "seg", os.path.join(PROJECT_ROOT, "08_segment_transcripts.py"))
seg = importlib.util.module_from_spec(_sspec)
_sspec.loader.exec_module(seg)

MEASURES = t14.MEASURES
YEARS = t14.YEARS
CONTEXTS = ["prepared_management", "managerial_qa"]
PRETTY = t14.PRETTY

VALIDATIONS: list[dict] = []


def check(rule: str, passed: bool, detail: str = "") -> bool:
    VALIDATIONS.append({"rule": rule, "result": "PASS" if passed else "FAIL",
                        "detail": detail})
    return passed


def build_holm_table(prep: pd.DataFrame, qa: pd.DataFrame) -> pd.DataFrame:
    """Year contrasts with Holm adjustment applied WITHIN each family.

    THE FAMILY DEFINITION MATTERS AND IS DELIBERATE.
    Holm is applied only across the THREE year contrasts (FY2022, FY2023,
    FY2024 vs FY2021) belonging to the SAME measure x communication context.
    That is the set of comparisons generated by one model answering one
    question, so it is the natural family.

    A single global correction across all 24 contrasts (4 measures x 2 contexts
    x 3 years) is deliberately NOT applied: the four linguistic measures answer
    different substantive questions and the two contexts are separate models,
    so pooling them would penalise each contrast for comparisons that are not
    part of its own inferential claim.

    The overall categorical fiscal-year Wald test is NOT Holm-adjusted -- it is
    a single omnibus test per model, not a family of comparisons.
    """
    rows = []
    for ctx, df in ((CONTEXTS[0], prep), (CONTEXTS[1], qa)):
        for meas in MEASURES:
            # Same specification as Task 14 -- re-fitted, not redefined.
            f = t14.fit_year_model(df, meas, ctx)
            fam = []
            for y in YEARS[1:]:
                fam.append(dict(
                    communication_context=ctx, measure=meas,
                    contrast=f"FY{y} vs FY2021",
                    contrast_year=y,
                    estimate=f[f"coef_{y}"], std_error=f[f"se_{y}"],
                    ci_lower=f[f"ci_low_{y}"], ci_upper=f[f"ci_high_{y}"],
                    p_raw=f[f"p_{y}"],
                    overall_year_wald_chi2=f["overall_year_wald_chi2"],
                    overall_year_df=f["overall_year_df"],
                    overall_year_p=f["overall_year_p"],
                    icc_firm=f["icc_firm"], n_obs=f["n_obs"],
                    n_firms=f["n_groups"]))
            praw = [r["p_raw"] for r in fam]
            _, padj, _, _ = multipletests(praw, alpha=0.05, method="holm")
            for r, pa in zip(fam, padj):
                r["p_holm"] = float(pa)
                r["sig_raw_05"] = int(r["p_raw"] < 0.05)
                r["sig_holm_05"] = int(pa < 0.05)
                r["holm_family"] = f"{ctx} | {meas} (3 year contrasts)"
                r["changed_by_holm"] = int(r["sig_raw_05"] != r["sig_holm_05"])
            rows += fam
    return pd.DataFrame(rows)


def interpret_rq1(holm: pd.DataFrame, desc: pd.DataFrame) -> pd.DataFrame:
    """Separate the DESCRIPTIVE pattern from the statistically supported claim.

    A descriptive pattern is a statement about the yearly means and does not
    change because a contrast loses significance after adjustment. The
    inferential claim is a statement about which contrasts remain supported.
    Reporting them as one sentence is what produces overstated Results
    sections, so they are kept in separate fields here.
    """
    rows = []
    for ctx in CONTEXTS:
        for meas in MEASURES:
            h = holm[(holm.communication_context == ctx)
                     & (holm.measure == meas)].sort_values("contrast_year")
            d = desc[(desc.measure == meas)
                     & (desc.communication_context == ctx)
                     & (desc.fiscal_year != "ALL")].sort_values("fiscal_year")
            means = d["mean"].tolist()
            overall_p = h.overall_year_p.iloc[0]
            raw_sig = [int(y) for y in h.loc[h.sig_raw_05 == 1, "contrast_year"]]
            holm_sig = [int(y) for y in h.loc[h.sig_holm_05 == 1, "contrast_year"]]

            # Descriptive shape -- from the means only, never from p-values.
            diffs = np.diff(means)
            if all(x > 0 for x in diffs):
                shape = "monotonically increasing across FY2021-FY2024"
            elif all(x < 0 for x in diffs):
                shape = "monotonically decreasing across FY2021-FY2024"
            else:
                peak = YEARS[int(np.argmax(means))]
                trough = YEARS[int(np.argmin(means))]
                shape = (f"non-monotonic (highest FY{peak}, lowest FY{trough})")

            # Inferential statement, worded to avoid overstating a null.
            if overall_p >= 0.05:
                infer = (f"no detectable temporal variation in this sample "
                         f"(omnibus year test p={overall_p:.3f}); this is an "
                         f"absence of detectable variation, NOT evidence that "
                         f"the measure is constant over time")
            elif holm_sig:
                infer = (f"omnibus year effect detected (p={overall_p:.4f}); "
                         f"contrasts remaining supported after Holm: "
                         f"{', '.join('FY'+str(y) for y in holm_sig)}")
            else:
                infer = (f"omnibus year effect detected (p={overall_p:.4f}), but "
                         f"NO individual year contrast survives Holm adjustment")
            rows.append(dict(
                communication_context=ctx, measure=meas,
                yearly_means="; ".join(f"FY{y}={m:.5f}"
                                       for y, m in zip(YEARS, means)),
                descriptive_pattern=shape,
                overall_year_p=overall_p,
                contrasts_sig_raw=", ".join('FY'+str(y) for y in raw_sig) or "none",
                contrasts_sig_holm=", ".join('FY'+str(y) for y in holm_sig) or "none",
                n_contrasts_changed_by_holm=int(h.changed_by_holm.sum()),
                inferential_statement=infer))
    return pd.DataFrame(rows)


def build_rq2_final(pair: pd.DataFrame) -> pd.DataFrame:
    """RQ2 standardised on ONE estimand and ONE primary test for all measures.

    WHY STANDARDISE.
    Task 14 selected the primary test per measure from the shape of the paired
    differences, which made Wilcoxon primary for LM uncertainty and the paired
    t-test primary for the other three. That is defensible test-by-test but it
    leaves the Results table reporting a mean difference for three measures and
    a rank statistic for the fourth -- two different estimands in one table.

    For reporting consistency the PRIMARY ESTIMAND is now the mean paired
    difference (Q&A minus prepared) for ALL four measures, with the paired
    t-test as the primary inferential test throughout. At n=350 the CLT makes
    the mean difference well behaved even for the more skewed LM uncertainty
    differences.

    The Wilcoxon test is RETAINED as a distributional robustness check, not as
    a replacement, and the two are compared explicitly per measure.
    """
    rows = []
    for meas in MEASURES:
        p_ = pair[f"prep_{meas}"]
        q_ = pair[f"qa_{meas}"]
        d = pair[f"diff_{meas}"]
        n = len(d)
        mean_d, sd_d = float(d.mean()), float(d.std(ddof=1))
        se = sd_d / np.sqrt(n)
        tcrit = st.t.ppf(0.975, n - 1)
        t_stat, t_p = st.ttest_rel(q_, p_)
        w_stat, w_p = st.wilcoxon(q_, p_)
        dz = mean_d / sd_d

        # Agreement is VERIFIED, not assumed: same direction and the same
        # significance conclusion at alpha = 0.05.
        agree_sig = (t_p < 0.05) == (w_p < 0.05)
        if agree_sig and t_p < 0.05:
            robust = ("conclusion unchanged: the Wilcoxon signed-rank test "
                      "agrees with the paired t-test in both direction and "
                      "significance")
        elif agree_sig:
            robust = ("conclusion unchanged: both tests find little evidence "
                      "of a systematic difference")
        else:
            robust = ("CONCLUSION DIFFERS between the paired t-test and the "
                      "Wilcoxon test -- report both and do not rely on either "
                      "alone")

        rows.append(dict(
            measure=meas, n_pairs=n,
            prepared_mean=float(p_.mean()), prepared_sd=float(p_.std(ddof=1)),
            qa_mean=float(q_.mean()), qa_sd=float(q_.std(ddof=1)),
            mean_difference=mean_d,
            ci_lower=mean_d - tcrit * se, ci_upper=mean_d + tcrit * se,
            cohens_dz=dz,
            paired_t_stat=float(t_stat), paired_t_p=float(t_p),
            wilcoxon_stat=float(w_stat), wilcoxon_p=float(w_p),
            diff_skewness=float(st.skew(d)), diff_kurtosis=float(st.kurtosis(d)),
            median_difference=float(d.median()),
            pct_pairs_qa_higher=float((d > 0).mean() * 100),
            robustness_interpretation=robust))
    return pd.DataFrame(rows)


def word_rq2(r: pd.Series) -> str:
    """Wording that does not overstate a non-significant result.

    A non-significant paired test means the data provide little evidence of a
    systematic difference -- it does NOT establish that no difference exists.
    The CI is quoted so the reader can see what magnitudes remain compatible
    with the data.
    """
    if r.paired_t_p >= 0.05:
        return (f"little evidence of a systematic prepared-versus-Q&A "
                f"difference in {PRETTY[r.measure]} (mean difference "
                f"{r.mean_difference:+.5f}, 95% CI [{r.ci_lower:+.5f}, "
                f"{r.ci_upper:+.5f}], dz={r.cohens_dz:+.3f}, p={r.paired_t_p:.3f}). "
                f"The interval is consistent with differences of either sign, "
                f"so this is an absence of detected difference rather than "
                f"evidence of equivalence.")
    direction = "higher" if r.mean_difference > 0 else "lower"
    return (f"managerial Q&A scores {direction} than prepared remarks on "
            f"{PRETTY[r.measure]} (mean difference {r.mean_difference:+.5f}, "
            f"95% CI [{r.ci_lower:+.5f}, {r.ci_upper:+.5f}], "
            f"dz={r.cohens_dz:+.3f}, paired t={r.paired_t_stat:.2f}, "
            f"p={r.paired_t_p:.2e}); Q&A is higher in "
            f"{r.pct_pairs_qa_higher:.1f}% of the {r.n_pairs} paired calls")


def main() -> None:
    R = seg.Report()
    R("TASK 14B -- FINALISE RQ1/RQ2 REPORTING")
    R(f"generated: {dt.datetime.now():%Y-%m-%d %H:%M:%S}")
    R(f"python {sys.version.split()[0]} | pandas {pd.__version__}")
    R("")
    R("Reporting and robustness cleanup ONLY. Preprocessing, analytical")
    R("samples, linguistic measures, model specification, eligibility rules,")
    R("company mappings and event windows are unchanged. Task 14 result tables")
    R("are NOT overwritten. RQ3 is not run.")

    prep, qa, pair = t14.load_samples()
    desc = pd.concat([t14.describe(prep, CONTEXTS[0]),
                      t14.describe(qa, CONTEXTS[1])], ignore_index=True)
    R("")
    R(f"samples re-loaded unchanged: prepared={len(prep)}, qa={len(qa)}, "
      f"paired={len(pair)}")

    # ---- RQ1 ------------------------------------------------------------
    R.head("RQ1 -- MODEL RETAINED UNCHANGED")
    R("   measure ~ C(fiscal_year), random intercept for firm, fitted")
    R("   separately for prepared_management and managerial_qa.")
    R("   Fiscal year categorical, FY2021 reference. No added controls.")
    R("   Estimates are identical to Task 14; only the reporting changes.")

    holm = build_holm_table(prep, qa)
    holm.to_csv(os.path.join(PROCESSED_DIR,
                             "14b_rq1_year_contrasts_holm.csv"), index=False)

    R.head("RQ1 -- HOLM ADJUSTMENT: FAMILY DEFINITION")
    R("Holm is applied within each family of the THREE year contrasts")
    R("belonging to the same measure x communication context -- the set of")
    R("comparisons generated by one model answering one question.")
    R("")
    R("A single GLOBAL correction across all 24 contrasts is deliberately NOT")
    R("applied: the four measures answer different substantive questions and")
    R("the two contexts are separate models, so pooling them would penalise")
    R("each contrast for comparisons outside its own inferential claim.")
    R("")
    R("The omnibus categorical fiscal-year Wald test is NOT Holm-adjusted: it")
    R("is one test per model, not a family of comparisons.")
    R(f"   families: {holm.groupby(['communication_context', 'measure']).ngroups} "
      f"x 3 contrasts = {len(holm)} contrasts")

    R.head("RQ1 -- YEAR CONTRASTS, RAW AND HOLM-ADJUSTED")
    for ctx in CONTEXTS:
        R("")
        R(f"=== {ctx} ===")
        for meas in MEASURES:
            h = holm[(holm.communication_context == ctx)
                     & (holm.measure == meas)].sort_values("contrast_year")
            R(f"\n  {PRETTY[meas]}   omnibus year p="
              f"{h.overall_year_p.iloc[0]:.4f}  (ICC={h.icc_firm.iloc[0]:.3f})")
            R(f"    {'contrast':<18s}{'estimate':>11s}{'se':>10s}"
              f"{'95% CI':>24s}{'p_raw':>10s}{'p_holm':>10s}{'':>4s}")
            for _, r in h.iterrows():
                mark = ""
                if r.changed_by_holm:
                    mark = "  <-- lost significance under Holm"
                elif r.sig_holm_05:
                    mark = "  *"
                R(f"    {r.contrast:<18s}{r.estimate:>+11.5f}{r.std_error:>10.5f}"
                  f"   [{r.ci_lower:+.5f}, {r.ci_upper:+.5f}]"
                  f"{r.p_raw:>10.4f}{r.p_holm:>10.4f}{mark}")

    changed = holm[holm.changed_by_holm == 1]
    R.head("RQ1 -- DID HOLM ADJUSTMENT CHANGE ANY CONCLUSION?")
    R(f"contrasts significant at raw p<0.05  : {int(holm.sig_raw_05.sum())} of {len(holm)}")
    R(f"contrasts significant after Holm     : {int(holm.sig_holm_05.sum())} of {len(holm)}")
    R(f"contrasts whose conclusion CHANGED   : {len(changed)}")
    if len(changed):
        for _, r in changed.iterrows():
            R(f"   {r.communication_context} | {r.measure} | {r.contrast}: "
              f"p_raw={r.p_raw:.4f} -> p_holm={r.p_holm:.4f} "
              f"(no longer significant at 0.05)")
    else:
        R("   none -- every contrast keeps its significance status under Holm.")

    interp = interpret_rq1(holm, desc)
    R.head("RQ1 -- FINAL INTERPRETATION (DESCRIPTIVE vs INFERENTIAL)")
    R("The descriptive pattern describes the yearly MEANS and does not change")
    R("when a contrast loses significance. The inferential statement says which")
    R("contrasts remain supported. They are reported separately on purpose.")
    for ctx in CONTEXTS:
        R("")
        R(f"=== {ctx} ===")
        for _, r in interp[interp.communication_context == ctx].iterrows():
            R(f"\n  {PRETTY[r.measure]}")
            R(f"     means        : {r.yearly_means}")
            R(f"     descriptive  : {r.descriptive_pattern}")
            R(f"     inferential  : {r.inferential_statement}")
            R(f"     contrasts    : raw {r.contrasts_sig_raw}  |  "
              f"Holm {r.contrasts_sig_holm}")

    R.head("RQ1 -- RE-CHECKING THE THREE PREVIOUSLY STATED CLAIMS")
    claims = [
        ("prepared LM uncertainty declines in FY2023/FY2024 vs FY2021",
         CONTEXTS[0], "lm_uncertainty", [2023, 2024]),
        ("prepared LM negative is concentrated in FY2022",
         CONTEXTS[0], "lm_negative", [2022]),
        ("positive tone shows a non-monotonic pattern (both contexts)",
         None, "lm_positive", None),
    ]
    for text, ctx, meas, yrs in claims:
        R("")
        R(f"CLAIM: {text}")
        if ctx is None:
            for c in CONTEXTS:
                i = interp[(interp.communication_context == c)
                           & (interp.measure == meas)].iloc[0]
                R(f"   {c}: descriptive pattern = {i.descriptive_pattern}; "
                  f"Holm-supported contrasts = {i.contrasts_sig_holm}")
            R("   VERDICT: the descriptive non-monotonic shape is confirmed in")
            R("   both contexts and is unaffected by Holm adjustment.")
        else:
            h = holm[(holm.communication_context == ctx)
                     & (holm.measure == meas)
                     & (holm.contrast_year.isin(yrs))]
            for _, r in h.iterrows():
                R(f"   {r.contrast}: estimate {r.estimate:+.5f} "
                  f"[{r.ci_lower:+.5f}, {r.ci_upper:+.5f}], "
                  f"p_raw={r.p_raw:.4f}, p_holm={r.p_holm:.4f} -> "
                  f"{'SUPPORTED after Holm' if r.sig_holm_05 else 'NOT supported after Holm'}")
            ok = bool(h.sig_holm_05.all())
            R(f"   VERDICT: claim {'HOLDS' if ok else 'DOES NOT FULLY HOLD'} "
              f"after Holm adjustment.")

    # ---- RQ2 ------------------------------------------------------------
    rq2 = build_rq2_final(pair)
    rq2.to_csv(os.path.join(PROCESSED_DIR,
                            "14b_rq2_reporting_final.csv"), index=False)

    R.head("RQ2 -- STANDARDISED PRIMARY ESTIMAND AND TEST")
    R("PRIMARY for all four measures: the mean paired difference")
    R("(managerial_qa minus prepared_management) with its 95% CI, Cohen's dz,")
    R("and the paired t-test.")
    R("")
    R("Task 14 chose the primary test per measure from the shape of the paired")
    R("differences, which made Wilcoxon primary for LM uncertainty only. That")
    R("left one Results table mixing two estimands. The estimand is now the")
    R("same for all four measures; at n=350 the CLT makes the mean difference")
    R("well behaved even for the more skewed LM uncertainty differences.")
    R("")
    R("Wilcoxon is RETAINED as a distributional robustness check. It does NOT")
    R("replace the primary paired-mean analysis.")
    R("")
    R(f"  {'measure':<17s}{'n':>5s}{'prep mean':>11s}{'qa mean':>10s}"
      f"{'mean diff':>11s}{'95% CI':>26s}{'dz':>8s}{'t':>10s}{'p':>11s}")
    for _, r in rq2.iterrows():
        R(f"  {r.measure:<17s}{r.n_pairs:>5d}{r.prepared_mean:>11.5f}"
          f"{r.qa_mean:>10.5f}{r.mean_difference:>+11.5f}"
          f"   [{r.ci_lower:+.5f}, {r.ci_upper:+.5f}]{r.cohens_dz:>+8.3f}"
          f"{r.paired_t_stat:>10.2f}{r.paired_t_p:>11.2e}")

    R.head("RQ2 -- WILCOXON AS DISTRIBUTIONAL ROBUSTNESS (VERIFIED, NOT ASSUMED)")
    R(f"  {'measure':<17s}{'diff skew':>11s}{'t p-value':>13s}"
      f"{'Wilcoxon p':>13s}{'agree?':>9s}")
    for _, r in rq2.iterrows():
        agree = (r.paired_t_p < 0.05) == (r.wilcoxon_p < 0.05)
        R(f"  {r.measure:<17s}{r.diff_skewness:>+11.3f}{r.paired_t_p:>13.2e}"
          f"{r.wilcoxon_p:>13.2e}{'yes' if agree else 'NO':>9s}")
    R("")
    for _, r in rq2.iterrows():
        R(f"  {r.measure}: {r.robustness_interpretation}")
    R("")
    R("LM uncertainty is the measure this check matters most for -- its paired")
    R(f"differences are the most skewed (skew="
      f"{rq2.loc[rq2.measure == 'lm_uncertainty', 'diff_skewness'].iloc[0]:+.3f}) "
      f"-- and the two tests agree.")

    R.head("RQ2 -- FINAL WORDING FOR THE RESULTS SECTION")
    R("Worded so that a non-significant result is not reported as evidence of")
    R("no difference.")
    for _, r in rq2.iterrows():
        R("")
        R(f"  {PRETTY[r.measure]}:")
        R(f"     {word_rq2(r)}")

    # ---- Fog robustness statement ---------------------------------------
    R.head("FOG ROBUSTNESS -- REPORTING STATEMENT (RESULTS RETAINED, NOT RERUN)")
    rob = pd.read_csv(os.path.join(PROCESSED_DIR,
                                   "14_fog_robustness_results.csv"))
    p2 = rob[(rob.analysis == "RQ2_paired") & (rob.fog_version == "primary")].iloc[0]
    f2 = rob[(rob.analysis == "RQ2_paired")
             & (rob.fog_version == "fathom_robustness")].iloc[0]
    R("The Fog measure is NOT rerun or redefined here; the Task 14 robustness")
    R("results are retained as computed.")
    R("")
    R("  * Primary Fog results use the Task 10 `fog_index`.")
    R("  * The Fathom-based implementation -- corresponding to the")
    R("    Lingua::EN::Fathom package used by Li (2008) -- is the robustness")
    R("    measure (`fog_index_fathom_robustness`, Entry 12).")
    R("  * The RQ1 and RQ2 substantive interpretations are UNCHANGED under the")
    R("    alternative measure.")
    R("")
    R("The two implementations are NOT numerically identical and must not be")
    R("described as such:")
    R(f"     RQ2 paired difference   primary {p2.mean_difference:+.4f} vs "
      f"Fathom {f2.mean_difference:+.4f} "
      f"({abs(f2.mean_difference - p2.mean_difference):.4f} apart)")
    r1 = rob[rob.analysis == "RQ1_year_effects"]
    for ctx in CONTEXTS:
        a = r1[(r1.context == ctx) & (r1.fog_version == "primary")].iloc[0]
        b = r1[(r1.context == ctx)
               & (r1.fog_version == "fathom_robustness")].iloc[0]
        R(f"     RQ1 {ctx:<20s} omnibus p {a.overall_year_p:.4f} vs "
          f"{b.overall_year_p:.4f} (both non-significant; same conclusion, "
          f"different numbers)")
    return R, holm, interp, rq2, prep, qa, pair


def validate(R, holm, rq2, prep, qa, pair) -> None:
    R.head("VALIDATION")
    check("samples unchanged: 350 / 367 / 350",
          len(prep) == 350 and len(qa) == 367 and len(pair) == 350,
          f"{len(prep)}/{len(qa)}/{len(pair)}")
    check("24 year contrasts (4 measures x 2 contexts x 3 years)",
          len(holm) == 24, f"got {len(holm)}")
    check("Holm applied within 8 families of 3 contrasts",
          holm.groupby(["communication_context", "measure"]).size().eq(3).all())
    check("Holm p never below the raw p (adjustment can only increase it)",
          bool((holm.p_holm >= holm.p_raw - 1e-12).all()))
    check("Holm p never exceeds 1", bool((holm.p_holm <= 1.0 + 1e-12).all()))
    check("RQ2 covers all four measures with n=350 each",
          len(rq2) == 4 and bool((rq2.n_pairs == 350).all()))
    check("RQ2 primary estimand is the mean paired difference for all measures",
          bool(rq2.mean_difference.notna().all()
               and rq2.ci_lower.notna().all() and rq2.cohens_dz.notna().all()))
    check("paired t-test reported as primary for all four measures",
          bool(rq2.paired_t_p.notna().all()))
    check("Wilcoxon retained for all four measures as robustness",
          bool(rq2.wilcoxon_p.notna().all()))
    # Verify the stated robustness expectations rather than assuming them.
    agree = [( (r.paired_t_p < 0.05) == (r.wilcoxon_p < 0.05) )
             for _, r in rq2.iterrows()]
    check("paired-t and Wilcoxon agree on significance for every measure",
          all(agree), f"disagreements: "
                      f"{[m for m, a in zip(rq2.measure, agree) if not a]}")
    check("Task 14 result tables not overwritten",
          all(os.path.exists(os.path.join(PROCESSED_DIR, f)) for f in
              ("14_rq1_descriptive.csv", "14_rq1_inferential.csv",
               "14_rq2_paired_results.csv", "14_rq2_by_year.csv",
               "14_fog_robustness_results.csv")))
    # The re-fitted estimates must match Task 14 exactly -- the model was not
    # changed, so any difference would mean something was altered.
    t14tab = pd.read_csv(os.path.join(PROCESSED_DIR, "14_rq1_inferential.csv"))
    mism = 0
    for _, r in holm.iterrows():
        m = t14tab[(t14tab.context == r.communication_context)
                   & (t14tab.measure == r.measure)]
        if len(m) and abs(float(m[f"coef_{r.contrast_year}"].iloc[0])
                          - r.estimate) > 1e-9:
            mism += 1
    check("re-fitted coefficients identical to Task 14 (model unchanged)",
          mism == 0, f"{mism} mismatching coefficients")

    v = pd.DataFrame(VALIDATIONS)
    for _, r in v.iterrows():
        R(f"   [{'PASS' if r['result'] == 'PASS' else '**FAIL**'}] {r['rule']}"
          + (f"  -- {r['detail']}" if r["detail"] else ""))
    nf = int((v["result"] == "FAIL").sum())
    R("")
    R(f"validation rules checked: {len(v)}   failures: {nf}")
    v.to_csv(os.path.join(QC_DIR, "14b_validation_results.csv"), index=False)


if __name__ == "__main__":
    _R, _holm, _interp, _rq2, _prep, _qa, _pair = main()
    validate(_R, _holm, _rq2, _prep, _qa, _pair)

    _R.head("OUTPUTS WRITTEN")
    for f in ("processed/14b_rq1_year_contrasts_holm.csv",
              "processed/14b_rq2_reporting_final.csv",
              "qc/14b_rq1_rq2_reporting_report.txt",
              "qc/14b_validation_results.csv"):
        _R(f"   {os.path.join(PROJECT_ROOT, f)}")
    _R("")
    _R("Task 14 tables retained unchanged: 14_rq1_descriptive.csv,")
    _R("14_rq1_inferential.csv, 14_rq2_paired_results.csv, 14_rq2_by_year.csv,")
    _R("14_fog_robustness_results.csv, and all figures.")
    _R.head("NOT DONE IN THIS TASK")
    _R("   RQ3; layoff-event analysis; Discussion writing. No analytical sample,")
    _R("   measure, or model specification was modified.")
    with open(os.path.join(QC_DIR, "14b_rq1_rq2_reporting_report.txt"), "w") as fh:
        fh.write(_R.text())
